### ISSUE TITLE
Scanning stop arm64/docker without error message

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#175]
I am using 2.10.3 built for arm64 under a docker container (on an NVIDIA Jetson Nano) and I am having the same problem: the scanning just stops without any error message. This happens if I use 1 single thread or more threads, the only thing is that if I am using more threads it happens very quickly...

Another thing is that if I use the `--fast` switch the problem does not happen, so it might be related to parsing file contents.

_Originally posted by @waltermaldonado in https://github.com/simon987/sist2/issues/147#issuecomment-897764555_

**Comment by simon987** [comment]
@waltermaldonado are you using a docker image from docker.io/simon987/sist2 or did you build the image yourself? I don't think I built an image for v2.10.3

**Comment by waltermaldonado** [comment]
I tried with `simon987/sist2-arm64:latest` and built one in my own device adding tesseract data for portuguese (v2.10.3). You can pull the image from `walterbode/my-sist2`.

Another info that might be of interest is that I am scanning ~700GB of files (~1mi) in an external USB 3.0 hd.

**Comment by simon987** [comment]
`simon987/sist2-arm64` is very old and I think that the latest arm64 image I pushed was for 2.10.1 (`simon987/sist2:2.10.1-arm64-linux`).

In next few days I will push a 'debug' image for arm64 which will print more information when crashing and should help me find the issue more easily in the future. 

In the meantime if you want to help me debugging faster, you could build your image again following the information in the README, but set `SIST_DEBUG=on` on this line: https://github.com/simon987/sist2/blob/master/Dockerfile.arm64#L6, then try to scan again and paste the error message(s) here.

**Comment by waltermaldonado** [comment]
It really looks like there is some memory leaking during the scan. My swap gradually filled and froze the device.
After that, I constrained the Docker container memory to 1g and the scan halted at 1% (without `--very-verbose`).
Even with the debug binary and with `--very-verbose` on, there is no informative log message, just the last parsed file like any previous one.

Definitely the bug it is memory related. It runs ok if I shutdown any other process and leave 3.5g (+ swap) free so sist2 can use it, at least untill it fills all the device's memory.

Now I am trying it with 2g.

**Comment by waltermaldonado** [comment]
Today I decided to install sist2 on another machine (Docker - x64 - `simon987/sist2` image) in the network and try do index files over smb.
After running the scan for a while it crashed with the log:
```
...
[7FCBDDD09640] [2021-08-13 15:21:34] [INFO *SIGNAL HANDLER*] Please consider creating a bug report at https://github.com/simon987/sist2/issues ! 
[7FCBDDD09640] [2021-08-13 15:21:34] [INFO *SIGNAL HANDLER*] sist2 is an open source project and relies on the collaboration of its users to diagnose and fix bugs 
[7FCBDDD09640] [2021-08-13 15:21:34] [ERROR *SIGNAL HANDLER*] =============================================

 
[7FCBDDD09640] [2021-08-13 15:21:34] [ERROR *SIGNAL HANDLER*] Uh oh! Caught fatal signal: Segmentation fault
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDED0B640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO6.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDE50A640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO7 - Entregue - Melhor.pdf
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDDD09640] was working on job /files/Warehouse/DOCUMENTOS/Biosystems Engineering/YBENG_2018_360_Revision 1_V0/YBENG_2018_360_R1.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDD508640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO4 - Protocolada - Maruyama.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDFD0D640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO4 - Protocolada - Renata.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDF50C640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO4 - Protocolada.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->thread_cnt = 6
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->work_cnt = 20388
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->done_cnt = 16054
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->stop = 0
[7FCBDDD09640] [2021-08-13 15:21:34] [INFO *SIGNAL HANDLER*] Please consider creating a bug report at https://github.com/simon987/sist2/issues ! 
[7FCBDDD09640] [2021-08-13 15:21:34] [INFO *SIGNAL HANDLER*] sist2 is an open source project and relies on the collaboration of its users to diagnose and fix bugs 
[7FCBDDD09640] [2021-08-13 15:21:34] [ERROR *SIGNAL HANDLER*] =============================================

 
[7FCBDDD09640] [2021-08-13 15:21:34] [ERROR *SIGNAL HANDLER*] Uh oh! Caught fatal signal: Segmentation fault
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDED0B640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO6.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDE50A640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO7 - Entregue - Melhor.pdf
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDDD09640] was working on job /files/Warehouse/DOCUMENTOS/Biosystems Engineering/YBENG_2018_360_Revision 1_V0/YBENG_2018_360_R1.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDD508640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO4 - Protocolada - Maruyama.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDFD0D640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO4 - Protocolada - Renata.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDF50C640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO4 - Protocolada.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->thread_cnt = 6
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->work_cnt = 20388
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->done_cnt = 16054
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->stop = 0
[7FCBDDD09640] [2021-08-13 15:21:34] [INFO *SIGNAL HANDLER*] Please consider creating a bug report at https://github.com/simon987/sist2/issues ! 
[7FCBDDD09640] [2021-08-13 15:21:34] [INFO *SIGNAL HANDLER*] sist2 is an open source project and relies on the collaboration of its users to diagnose and fix bugs 
[7FCBDDD09640] [2021-08-13 15:21:34] [ERROR *SIGNAL HANDLER*] =============================================

 
[7FCBDDD09640] [2021-08-13 15:21:34] [ERROR *SIGNAL HANDLER*] Uh oh! Caught fatal signal: Segmentation fault
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDED0B640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO6.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDE50A640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO7 - Entregue - Melhor.pdf
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDDD09640] was working on job /files/Warehouse/DOCUMENTOS/Biosystems Engineering/YBENG_2018_360_Revision 1_V0/YBENG_2018_360_R1.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDD508640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO4 - Protocolada - Maruyama.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDFD0D640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO4 - Protocolada - Renata.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG *SIGNAL HANDLER*] THREAD [7FCBDF50C640] was working on job /files/Warehouse/DOCUMENTOS/Cosmopolites Sordidus/DISSERTAÇÃO4 - Protocolada.docx
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->thread_cnt = 6
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->work_cnt = 20388
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->done_cnt = 16054
[7FCBDDD09640] [2021-08-13 15:21:34] [DEBUG tpool.c] pool->stop = 0
```
PS: I had to kill the container to stop the infinite log loop.

**Comment by waltermaldonado** [comment]
Well, it looks like there is not enough power being delivered to the HD, I grabbed this from `dmesg`:
```
[  443.224826] scsi host1: uas_eh_bus_reset_handler start
[  443.310525] usb 2-1.2: reset SuperSpeed USB device number 3 using tegra-xusb
[  443.333383] scsi host1: uas_eh_bus_reset_handler success
[  455.273243] JBD2: Detected IO errors while flushing file data on sda1-8
[  455.279945] Aborting journal on device sda1-8.
[  456.267972] JBD2: Detected IO errors while flushing file data on sda1-8
[  458.197733] sd 1:0:0:0: [sda] tag#3 uas_eh_abort_handler 0 uas-tag 4 inflight: CMD IN
[  458.197740] sd 1:0:0:0: [sda] tag#3 CDB: opcode=0x88 88 00 00 00 00 00 3a eb 94 40 00 00 01 00 00 00
[  458.197958] sd 1:0:0:0: [sda] tag#0 uas_eh_abort_handler 0 uas-tag 1 inflight: CMD IN
[  458.197963] sd 1:0:0:0: [sda] tag#0 CDB: opcode=0x88 88 00 00 00 00 00 3a eb 93 40 00 00 01 00 00 00
[  458.237525] scsi host1: uas_eh_bus_reset_handler start
[  458.237550] EXT4-fs error (device sda1): ext4_journal_check_start:56: Detected aborted journal
[  458.246240] EXT4-fs (sda1): Remounting filesystem read-only
[  458.322818] usb 2-1.2: reset SuperSpeed USB device number 3 using tegra-xusb
[  458.355257] scsi host1: uas_eh_bus_reset_handler success
[  460.181704] sd 1:0:0:0: [sda] tag#3 uas_eh_abort_handler 0 uas-tag 4 inflight: CMD IN
[  460.181711] sd 1:0:0:0: [sda] tag#3 CDB: opcode=0x88 88 00 00 00 00 00 bf 19 aa 40 00 00 00 40 00 00
[  460.181958] sd 1:0:0:0: [sda] tag#2 uas_eh_abort_handler 0 uas-tag 3 inflight: CMD OUT
[  460.181962] sd 1:0:0:0: [sda] tag#2 CDB: opcode=0x8a 8a 00 00 00 00 00 00 00 08 00 00 00 00 08 00 00
[  460.182142] sd 1:0:0:0: [sda] tag#1 uas_eh_abort_handler 0 uas-tag 2 inflight: CMD IN
[  460.182146] sd 1:0:0:0: [sda] tag#1 CDB: opcode=0x88 88 00 00 00 00 00 3a eb 93 40 00 00 01 00 00 00
[  460.182334] sd 1:0:0:0: [sda] tag#0 uas_eh_abort_handler 0 uas-tag 1 inflight: CMD IN
[  460.182338] sd 1:0:0:0: [sda] tag#0 CDB: opcode=0x88 88 00 00 00 00 00 3a eb 94 40 00 00 01 00 00 00
[  460.182534] scsi host1: uas_eh_bus_reset_handler start
[  460.262258] usb 2-1.2: reset SuperSpeed USB device number 3 using tegra-xusb
[  460.288793] scsi host1: uas_eh_bus_reset_handler success
[  462.357324] EXT4-fs error (device sda1): ext4_journal_check_start:56: Detected aborted journal
```

Problem is being taken care of, I already bought a powered USB hub and will keep you posted...

**Comment by waltermaldonado** [comment]
I installed the powered USB hub and the problem persisted. It happens the USB-SATA interface announces it supports UAS but it does not work with some kernels, including some RPi and JetsonNano ones. I blacklisted UAS and now I am using regular `usb-storage`, and the USB reset problem was totally fixed.

After that I tried to run the scan process both from the JetsonNano and from a x64 pc through Samba, but in both cases the problem is still happening, getting into an infinite segmentation fault loop.

**Comment by simon987** [comment]
Thanks for checking. Did you notice if the same files are printed (where it says `THREAD [7FCBDED0B640] was working on job ...`) with the new attempt? If so, would you be able to privately send the files to me at `me@simon987.net` ?

**Comment by waltermaldonado** [comment]
Even though the files are different, the bug is consistent within the files (there seems to be a lot of problematic ones... 😄).

**Comment by simon987** [comment]
Thanks a lot!
I was also able to reproduce the bug on my side and found a fix for this type of files (the .docx had an xml tag without a name for some reason). 

I pushed a fix in the `dev` branch 9c0f3e0e31db436d8934a0608753ecd69ea14890. If you're building from source, you should no longer see that error.

**Comment by waltermaldonado** [comment]
Just tested and it worked perfectly!

Also, congrats for the great job. There is no other tool on the internet that does what you did here, specially on low-powered ARM devices. And it is really fast! 

Thank you very much!
